Update Juneteenth with observed dates
azuyalabs/yasumi pull request #282
Opened 2022-06-20 16:42 UTC by tylershuster

2022-06-21 14:23 UTC, stelgenhof commented
Hi @tylershuster Thanks for the PR! Can you please add some unit tests? Please see also: https://github.com/azuyalabs/yasumi/blob/develop/CONTRIBUTING.md
Thanks!

2022-06-22 15:26 UTC, tylershuster commented
Will do. Sorry about the commit history; I'll clean that up. I'm a little confused about the [existing unit tests](https://github.com/azuyalabs/yasumi/blob/develop/tests/USA/JuneteenthTest.php) because it seems to already test for the change I added! (minus the "(observed)" portion)

2022-07-29 21:03 UTC, tylershuster commented
Please pardon my tardiness. Things seem to be in order, so please review.

2022-08-11 07:30 UTC, stelgenhof commented
@tylershuster Reran the checks and there seem to be some code style issues.

2022-09-05 07:19 UTC, stelgenhof commented
@tylershuster Can you check once more your PR as there some minor errors? I'd like to include this fix in the next release I am planning. Thanks!

2022-09-05 15:57 UTC, tylershuster commented
@stelgenhof I think the style is fine now — PHPCS doesn't throw any errors.

2022-09-07 02:08 UTC, stelgenhof requested changes

2022-09-07 02:08 UTC, stelgenhof commented on src/Yasumi/Provider/USA.php
> +            if ('Sunday' === $date->format('l')) {
I'd recommend to use the 'w' formatter (A numeric representation of the day (0 for Sunday, 6 for Saturday)) instead, as the string representation of the week day is less certain to be stable (may have future changes in casing, naming, etc.)

2022-09-07 02:08 UTC, stelgenhof commented on src/Yasumi/Provider/USA.php
> +            } elseif ('Saturday' === $date->format('l')) {
I'd recommend to use the 'w' formatter (A numeric representation of the day (0 for Sunday, 6 for Saturday)) instead, as the string representation of the week day is less certain to be stable (may have future changes in casing, naming, etc.)

2022-09-07 02:08 UTC, stelgenhof commented on src/Yasumi/Provider/USA.php
> +          ], $date, $this->locale));
For holidays that are observed/substituted due to that they may fall in the weekend for example, you should use the `SubstituteHoliday` class.

2022-09-07 16:17 UTC, tylershuster commented
Thanks for the feedback. I think those issues are cleaned up. I tried to pattern it after an existing substitute holiday

2022-09-20 18:14 UTC, tylershuster commented on tests/USA/JuneteenthTest.php
> +     *
I can do that. I don't see a test for this particular method for substituted holidays. I was just going to let it generate a random year now that it generates substitute holidays properly.

2022-10-31 23:20 UTC, tylershuster commented
Failure seems...incorrect

2022-12-27 08:24 UTC, stelgenhof approved these changes

2022-12-28 00:12 UTC, stelgenhof commented
The unsuccessful checks are not directly related to this PR. I will merge it and resolve these afterwards.

2022-12-28 00:12 UTC, merged