WIP: Added Holiday for Cyprus.
azuyalabs/yasumi pull request #285
Opened 2022-08-11 03:08 UTC by bkintanar

2022-09-05 07:17 UTC, stelgenhof commented
@bkintanar I think so far it looks good (the tests are green :+1: ) Are these all of the national holidays of Cyprus?

2022-09-05 07:28 UTC, bkintanar commented
@stelgenhof no. easterTuesday is a bank holiday. Should it be removed?

2022-09-05 07:36 UTC, stelgenhof commented
@bkintanar It can stay, as long as it has the appropriate category. Generally, for each country, all of the official, national holidays should be included in a provider. Any other holidays can of course be added as well.

2022-09-05 14:53 UTC, stelgenhof commented
@bkintanar Looking at your PR once more, I noticed that (from the list on https://en.wikipedia.org/wiki/Public_holidays_in_Cyprus) Easter Sunday seems to be missing. Also a number of unit tests for some holidays are not present. Please add unit tests for all the holidays defined by the provider.

2022-09-07 02:13 UTC, stelgenhof requested changes
Looking at your PR once more, I noticed that (from the list on https://en.wikipedia.org/wiki/Public_holidays_in_Cyprus) Easter Sunday seems to be missing. Also a number of unit tests for some holidays are not present. Please add unit tests for all the holidays defined by the provider.

2022-09-07 02:13 UTC, stelgenhof commented on src/Yasumi/Provider/Cyprus.php
> +        $this->addHoliday($this->epiphany($this->year, $this->timezone, $this->locale));
Please add unit test for this holiday.

2022-09-07 02:13 UTC, stelgenhof commented on src/Yasumi/Provider/Cyprus.php
> +        $this->addHoliday($this->christmasEve($this->year, $this->timezone, $this->locale));
Please add unit test for this holiday.

2022-09-07 02:13 UTC, stelgenhof commented on src/Yasumi/Provider/Cyprus.php
> +        $this->addHoliday($this->secondChristmasDay($this->year, $this->timezone, $this->locale));
Please add unit test for this holiday.

2022-09-07 02:13 UTC, stelgenhof commented on src/Yasumi/Provider/Cyprus.php
> +        $this->addHoliday($this->goodFriday($this->year, $this->timezone, $this->locale));
Please add unit test for this holiday.

2022-09-07 02:13 UTC, stelgenhof commented on src/Yasumi/Provider/Cyprus.php
> +        $this->addHoliday($this->pentecostMonday($this->year, $this->timezone, $this->locale));
Please add unit test for this holiday.

2022-09-07 02:13 UTC, stelgenhof commented on src/Yasumi/Provider/Cyprus.php
> +        $this->calculateGreekNationalDay();
Please add unit test for these holidays.

2022-12-18 00:35 UTC, closed without merging