handle invalid timezones Australia/ACT and Europe/Kiev
azuyalabs/yasumi pull request #343
Opened 2024-08-19 14:22 UTC by kevinpapst

Fixes #342

I hope the code comments explain the reasoning behind the changes.

All my systems seem to support both variants, but I had multiple bugs raised about `Australia/ACT` and `Europe/Kiev`.
Can't say when this happens, maybe it depends on the `tzdata` lib on the system where PHP was compiled. Or some PHP builds remove all timezone name which are only so called "links". 

In the official table (see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones ) both problematic TZ are only links, so I replaced them with their real TZ identifier.

2024-08-21 04:25 UTC, stelgenhof commented
Thank you very much @kevinpapst for this PR! Unfortunately there are sometimes backwards incompatible changes introduced in PHP. In the past there were similar BC issues with historical DST changes between PHP versions.

We could also move away from the timezone identifiers (type 3) altogether, and use the UTC offset (type 1) or the timezone abbreviation (type 2), as these seem less prone to changing. The benefit of the timezone identifier is of course it is more human friendlier than the other types.

2024-08-21 07:30 UTC, kevinpapst commented
Yeah, I fought in the past already with the `Kiev` removal, but that was in the scope of my time-tracking app, so I could take care of it myself. I use try&catch for it.

I think the timezone identifier is totally fine to use, it doesn't change regularly and the try&catch approach works flawless to handle this situation. Changing it to TZ offset would be a bigger BC break, as many of the `$timezone` variables are public and therefor you would change the public API. 

How to move forward?
1. Shall I change the the Australia class to try&catch as well? 
2. Never used psalm, what is the equivalent of `@phpstan-ignore-line` for the "dead catch" warning?

2024-08-21 08:58 UTC, stelgenhof commented
Yeah, wouldn't think the timezone identifier changes regularly either, but thought the others could be an option instead. However indeed that would break Yasumi's API :( 

I think the try&catch approach is a good approach. Please go ahead and use the same for Australia. Let me check on that dead catch issue in regards to Psalm.

2024-08-21 10:33 UTC, kevinpapst commented
I already did change Australia. 
And Psalm doesn't report it, it was only PHPStan. 
Checks are green, ready for review/merge from my end.

2024-08-28 14:24 UTC, stelgenhof requested changes
Looking good! Could add unit tests for this and update the Changelog as well?
Thanks!

2024-08-28 14:28 UTC, kevinpapst commented
Ok for the Changelog, but tell me how to test these changes.

The result depends on the environment / PHP runtime.

2024-09-10 14:23 UTC, thrashzone13 commented
Hi @stelgenhof  @kevinpapst !

I just wanted to suggest using [phpversion()](https://www.php.net/manual/en/function.phpversion.php) . It's self explaining and better than using a try catch

2024-09-10 16:28 UTC, kevinpapst commented
Does not depend on phpversion afaik, so this approach is not usable. 
Afaik this depends on the libicu version PHP was compiled against (or something like that, not sure about the exact internals). But the issue happened with PHP 8.1 and 8.3 and I have enough systems with these version where it doesn't happen.

2024-09-11 15:35 UTC, stelgenhof commented
I was thinking the same to use the PHP version for testing. If that turns out to be difficult, we can forgo the tests :)

2024-09-20 13:24 UTC, stelgenhof commented
@kevinpapst Can you only update the changelog? If done, then I'll merge it. Thanks!

2024-09-20 16:00 UTC, kevinpapst commented
@stelgenhof Changelog adjusted: done. 

Any chance you could create a bugfix release? I have production bugs with several users.

2024-09-20 16:01 UTC, kevinpapst commented on CHANGELOG.md
> +- Holiday calculation methods in providers are now protected instead of private
sorry, that must have been my IDE 🤷

2024-12-09 16:49 UTC, kevinpapst commented
Hello @stelgenhof ,

I keep on having users who run into this bug. I understand if you don't want to merge this: its open source, your product and there is no warranty given. But I am unfortunately getting bug/support requests every other week and I have no proper answer since a few months. 

I don't want to cause you any inconvenience here, please don't get that wrong: I appreciate your work and wanna thank you for sharing Yasumi! 

But I have to provide a bugfix after such a long time and I can't wait any longer. I don't want to maintain a fork, so I wanted to reach out one more time to ask, if you could share are plans. Is there any chance this gets incorporated anytime soon in a new release?
Is there anything I can do to push this forward?
Shall I recreate the PR from latest `develop` branch? The PR content doesn't look correct to me.

2024-12-11 09:40 UTC, kevinpapst commented
Just today:

```
[2024-12-11 10:11:44] [request] CRITICAL: Uncaught PHP Exception DateInvalidTimeZoneException: "DateTimeZone::__construct(): Unknown or bad timezone (Australia/ACT)" at DateTimeZoneFactory.php line 31 {"exception":"[object] (DateInvalidTimeZoneException(code: 0): DateTimeZone::__construct(): Unknown or bad timezone (Australia/ACT) at /www/htdocs/xxxxx/kimai/vendor/azuyalabs/yasumi/src/Yasumi/Provider/DateTimeZoneFactory.php:31)"} []
```

2024-12-11 13:54 UTC, stelgenhof commented
Hi @kevinpapst Let me have a look this weekend to make a release.

2025-01-07 15:17 UTC, stelgenhof commented
@kevinpapst Sorry to hear that. Unfortunately I haven't been able to work on it as much as I wanted. 
Having a quick look at your PR, it looks a bit odd. Besides some conflicts, it has over 1700 changed files. I assume your PR is not supposed to touch all source files.

2025-01-07 15:21 UTC, kevinpapst commented
As I said before: its open-source. I am not expecting anything. I am just sharing my experience. 

> Having a quick look at your PR, it looks a bit odd. Besides some conflicts, it has over 1700 changed files. I assume your PR is not supposed to touch all source files.

Which you force pushed into this branch 🤷 as I said before:

> Unfortunately the maintainer merged a whole bunch of unrelated stuff into this PR

2025-01-07 15:21 UTC, closed without merging